### PR TITLE
BlackPerl DFIR Academy

### PR DESCRIPTION
**Pull request by archanchoudhury**
Hello Florian, I am raising this PR to add BlackPerl DFIR Academy to be included in the repo. For the preview of the courses, our YouTube can be visited or each course in the academy comes up with some trail topics which can be viewed after a Free Sign Up.

### CODE REVIEW

**Comment by Neo23x0** [comment]
Hi Archan, 

thanks for the submission. 
Could you please list all 5/6 courses that you offer separately in the YAML file. You could check the YAML files of the other training providers for guidance.
You have 6 trainings. It should take you a lot of your time. 

Why did you decide against using a currency that most people know? (like e.g. USD)
I tried to select the price to copy it and paste it into a google search, but I cannot select it.
So I, as a user, have no idea what this currency is and how it converts to a currrently that I know. 
Screenshot 2023-05-26 at 11 20 47

**Comment by archanchoudhury** [comment]
Hello Florian,

Thanks for reverting back. Yes, I will convert the YAML file and make the adjustments. Actually we are coming up with more courses and the plan is to publish 1 course / month in this year. So do you want me to keep it editing?

For the currency, since we initially focused on India based users, and hence the platform payment gateway is configured to show INR as currency. However, when you try to buy a course outside of India, the payment gateway will convert that for you. Please see the screen shot below for USD:
image

Similarly people can choose the more option above as well to select their currency as they need.

**Review by cany1985 — APPROVED** [review]
-

**Comment by tracy0880550287** [comment]
Thanks for helping us maintain the quality of our codebase

**Comment by Neo23x0** [comment]
@archanchoudhury : I just noticed 

1. that you just gave me one training although you offer six

Screenshot 2023-05-30 at 17 26 35

Screenshot 2023-05-30 at 17 26 39

and 2. that I cannot copy & paste from your website, which is super annoying. 

I would've updated the YAML myself, but since I would have to type off every training title and description, I'm just removing you entry as long as the data is incomplete.

**Comment by Neo23x0** [comment]
You can work on the changes here: 
https://github.com/Cyber-Security-Hub/cyber-security-hub.github.io/pull/8

**Pull request merged**
