### PR TITLE
Create Adversary Cyber Security Expert Course

### PR DESCRIPTION
**Pull request by Ghostyboy0719**
Adding a Red teaming course here, let me know if it works

### CODE REVIEW

**Comment by Neo23x0** [comment]
I can't find any previews on the website

**Comment by Neo23x0** [comment]
How do you even get to that page? 
I tried finding it but failed. The web page is confusing. 

I can only see this: 
Screenshot 2023-05-26 at 11 27 44

Screenshot 2023-05-26 at 11 27 25

Please send me a direct link to the page that lists each of the courses. I cannot find it. 
Maybe other users have similar problems??

**Comment by Ghostyboy0719** [comment]
Oh my bad I will fix it. The course is offered through podia with this link. https://nexusinfosec.podia.com/acse-online-course

**Comment by Ghostyboy0719** [comment]
> Oh my bad I will fix it. The course is offered through podia with this link. https://nexusinfosec.podia.com/acse-online-course, you can add this link to the PR that would be great

Any updates

**Pull request merged**
